### ISSUE TITLE
Serializing / Deserializing with bincode may make results incompatible with other libraries.

### ISSUE THREAD

**Issue by nubis** [TotalKrill/simplestcrypt#1]
I'm using this library and making the results interact with javascript code using  https://github.com/miscreant/miscreant.js/

I would expect a serialized nonce+ciphertext to look like:
(16 bytes for the nonce) + (rest of bytes for ciphertext)

But bincode just adds 8 bytes in between so it looks like:
(16 bytes for the nonce + 8 bytes with size of the Vec + (rest of bytes for Vec ciphertext).

These extra 8 bytes make the serialized ciphertext be incompatible with miscreant, and maybe other libraries, so they have to be taken into account.

I know serialization is not part of the standard so there are no rights or wrongs, but the serialization used before converting to hex is specific to rust, so it may be worth mentioning in the readme if someone else runs into this.

Best!

edit: I looked into bincode to see what the extra 8 bytes were.

**Comment by TotalKrill** [comment]
Thank you for making me aware of this issue! I will for now just add a comment to the type, and add a section with this information into the readme!
